name: Update Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 추가: contents write 권한 명시

    steps:
    - name: Checkout
      uses: actions/checkout@v4  # v2 → v4 업데이트

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py

    - name: Push changes
      run: |
        git config --global user.name 'parang12'
        git config --global user.email 'gimt95513@gmail.com' 
        git add .
        git commit -m "Update velog posts" || echo "No changes"
        git pull origin main --rebase
        git push origin HEAD:main
